package lsystems;

public class LSystemSymbolException extends Exception{

    /**
     * Autogenerated Field
     */
    private static final long serialVersionUID = 170516637369596949L;

    private char symbol;

    public LSystemSymbolException(char symbol){
        this.symbol = symbol;
    }

    public char getSymbol(){
        return symbol;
    }

}
